
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_update = '''
"  let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
'''

[[plugins]] # Nvim-R
repo = 'jalvesaq/Nvim-R'
hook_add='''
  let maplocalleader = ","
   
  " deoplete
  " Use deoplete.
  let g:deoplete#enable_at_startup = 1
  " Use smartcase.
  let g:deoplete#enable_smart_case = 1
  " for Nvim-R
  if !exists('g:deoplete#omni_patterns')
      let g:deoplete#omni_patterns = {}
  endif
  let g:deoplete#omni_patterns.r = '[[:alnum:].\\]\+'
   
  " nvim-r
  let R_vsplit = 1
  let R_assign = 0
   
  let R_nvimpager = "horizontal"
   
  let R_objbr_place = "console,right"
  let R_objbr_opendf = 0

'''


[[plugins]]
repo = 'Shougo/neosnippet-snippets'


[[plugins]]
repo = 'cohama/lexima.vim'


[[plugins]]
repo = 'simeji/winresizer'


[[plugins]]
repo = 'mattn/emmet-vim'




