

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup   = 1
let g:deoplete#auto_complete_delay = 0
inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_add = '''
  let g:deoplete#sources#jedi#python_path = 'C:/Users/vigne/Anaconda3/envs/py36/python'

'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add='''
  nnoremap <silent> <space>fr :<C-u>Denite file_mru<CR>
  nnoremap <silent> <space>fb :<C-u>Denite buffer<CR>
  nnoremap <silent> <space>fy :<C-u>Denite neoyank<CR>
  nnoremap <silent> <space>ff :<C-u>Denite file<CR>
  nnoremap <silent> <space>fu :<C-u>Denite outline<CR>

  autocmd FileType denite call s:denite_my_settings()
  function! s:denite_my_settings() abort
    nnoremap <silent><buffer><expr> <CR>  denite#do_map('do_action')
    nnoremap <silent><buffer><expr> d  denite#do_map('do_action', 'delete')
    nnoremap <silent><buffer><expr> p  denite#do_map('do_action', 'preview')
    nnoremap <silent><buffer><expr> q  denite#do_map('quit')
    nnoremap <silent><buffer><expr> i  denite#do_map('open_filter_buffer')
    nnoremap <silent><buffer><expr> <Space>  denite#do_map('toggle_select').'j'
    nnoremap <silent><buffer><expr> a  denite#do_map('choose_action')
    nnoremap <silent><buffer><expr> c denite#do_map('do_action','cd')
    nnoremap <silent><buffer><expr> y denite#do_map('do_action','yank')
  endfunction

  autocmd FileType denite-filter call s:denite_filter_my_settings()

  function! s:denite_filter_my_settings() abort
    " toggle_select
    inoremap <silent><buffer<expr> <C-j> denite#do_map('toggle_select')
    " 一つ上のディレクトリを開き直す
    inoremap <silent><buffer><expr> <BS> denite#do_map('move_up_path')
    imap <silent><buffer> <C-o> <Plug>(denite_filter_quit)
    " Deniteを閉じる
    inoremap <silent><buffer><expr> <C-c> denite#do_map('quit')
    nnoremap <silent><buffer><expr> <C-c> denite#do_map('quit')
  endfunction
'''


[[plugins]] # Plugin to easily access Most Recently Used (MRU) files
repo = 'Shougo/neomru.vim'
on_source = 'denite.nvim'
on_path = '.*'

[[plugins]] # Yank
repo = 'Shougo/neoyank.vim'
on_source = 'denite.nvim'
on_event = 'TextYankPost'


[[plugins]] #
repo = 'kmnk/denite-dirmark'
on_source = 'denite.nvim'


[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  let g:neosnippet#snippets_directory = '$HOME/.cache/neosnippet/'

  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']



[[plugins]]
repo = 'suan/vim-instant-markdown'
on_ft = 'markdown'
hook_add = '''
  let g:deoplete#sources#jedi#python_path = 'C:/Users/vigne/Anaconda3/envs/py36/python'

'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add='''
  nnoremap <silent> <space>fr :<C-u>Denite file_mru<CR>
  nnoremap <silent> <space>fb :<C-u>Denite buffer<CR>
  nnoremap <silent> <space>fy :<C-u>Denite neoyank<CR>
  nnoremap <silent> <space>ff :<C-u>Denite file<CR>
  nnoremap <silent> <space>fu :<C-u>Denite outline<CR>

  autocmd FileType denite call s:denite_my_settings()
  function! s:denite_my_settings() abort
    nnoremap <silent><buffer><expr> <CR>  denite#do_map('do_action')
    nnoremap <silent><buffer><expr> d  denite#do_map('do_action', 'delete')
    nnoremap <silent><buffer><expr> p  denite#do_map('do_action', 'preview')
    nnoremap <silent><buffer><expr> q  denite#do_map('quit')
    nnoremap <silent><buffer><expr> i  denite#do_map('open_filter_buffer')
    nnoremap <silent><buffer><expr> <Space>  denite#do_map('toggle_select').'j'
    nnoremap <silent><buffer><expr> a  denite#do_map('choose_action')
    nnoremap <silent><buffer><expr> c denite#do_map('do_action','cd')
    nnoremap <silent><buffer><expr> y denite#do_map('do_action','yank')
  endfunction

  autocmd FileType denite-filter call s:denite_filter_my_settings()

  function! s:denite_filter_my_settings() abort
    " toggle_select
    inoremap <silent><buffer<expr> <C-j> denite#do_map('toggle_select')
    " 一つ上のディレクトリを開き直す
    inoremap <silent><buffer><expr> <BS> denite#do_map('move_up_path')
    imap <silent><buffer> <C-o> <Plug>(denite_filter_quit)
    " Deniteを閉じる
    inoremap <silent><buffer><expr> <C-c> denite#do_map('quit')
    nnoremap <silent><buffer><expr> <C-c> denite#do_map('quit')
  endfunction
'''


[[plugins]] # Plugin to easily access Most Recently Used (MRU) files
repo = 'Shougo/neomru.vim'
on_source = 'denite.nvim'
on_path = '.*'

[[plugins]] # Yank
repo = 'Shougo/neoyank.vim'
on_source = 'denite.nvim'
on_event = 'TextYankPost'


[[plugins]] #
repo = 'kmnk/denite-dirmark'
on_source = 'denite.nvim'


[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  let g:neosnippet#snippets_directory = '$HOME/.cache/neosnippet/'

  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']



